if(filename==""){
    endmacro;
}

disabledraw;
disablehistory 0x0041;

if (selecting == 1){
  // git blame -L startlineno, endlinenoファイル名
  $git = "git.exe blame -L " + str(seltopy) + "," + str(selendy) + " ";
}else{
  // git blame ファイル名
  $git = "git.exe blame ";
}

$$cmd = $git + filename2;
runex $$cmd
    , 1         //sync   0:async, 1:sync
    , 0, ""     //stdin  0:none, 1:auto, 2:<file, 3:(reserved),
                //       4:current content, 5:selection
    , 4, ""     //stdout 0:none, 1:auto, 2:>file 3:>>file, 4:new window,
                //       5:insert, 6:replace, 7:>output pane, 8:>>output pane
    , 4, ""     //stderr 0:none, 1:auto or >>stdout, 2-8:same as stdout's param
    , 0, ""     //folder 0:none, 1:current, 2:specify 3:(reserved), 4:exe's
    , 2         //show   0:auto, 1:show, 2:hide, 3-13:ShellExecute()'s SW_*
    , 1         //draw   0:draw, 1:no draw when stdout redirected
    , 6         //encode 0:ansi, 2:utf-16, 6:utf-8
    , 0         //extended flags
;

//runex の引数が 4:new window の場合はカーソルを先頭に持ってくる
moveto 0, 0;
