// git log --stat

$$git = "git.exe log --stat";
$$condition = input($$git + "\n条件を指定できます。");
if (result == false) {
  endmacro;
}
if ($$condition != "") {
  $$git = $$git + " --grep " + leftstr($$condition, 70);
}

disabledraw;
disablehistory 0x0041;

$$cmd = $$git;
$$dir = directory2 + "\\";
$$log = getenv("TMP") + "\\_logstat" + ".all" ;
runex $$cmd,0,0,"",2,$$log,0,"",2,$$dir,0,0,encode;
openfile "/r " + $$log;
