// git log format ファイル名

disabledraw;
disablehistory 0x0041;

$$target_file = "";
if (argcount > 0) {
  // 引数あり→呼び出しもとの引数でログをとる
  // 引数なし→ブランチ全体のログをとる
  $$target_file = getarg(0);
}

if ($$target_file == "") {
  $$git = "git.exe log --date=iso --pretty=format:\"[%ad] %h %an : %s\" ";
} else {
  $$git = "git.exe log --follow --date=iso --pretty=format:\"[%ad] %h %an : %s\" ";
}
$$cmd = $$git + $$target_file;
$$dir = directory2 + "\\";

runex $$cmd
    , 1         //sync   0:async, 1:sync
    , 0, ""     //stdin  0:none, 1:auto, 2:<file, 3:(reserved),
                //       4:current content, 5:selection
    , 4, ""     //stdout 0:none, 1:auto, 2:>file 3:>>file, 4:new window,
                //       5:insert, 6:replace, 7:>output pane, 8:>>output pane
    , 4, ""     //stderr 0:none, 1:auto or >>stdout, 2-8:same as stdout's param
    , 2, $$dir     //folder 0:none, 1:current, 2:specify 3:(reserved), 4:exe's
    , 2         //show   0:auto, 1:show, 2:hide, 3-13:ShellExecute()'s SW_*
    , 1         //draw   0:draw, 1:no draw when stdout redirected
    , 6         //encode 0:ansi, 2:utf-16, 6:utf-8
    , 0         //extended flags
;
//runex の引数が 4:new window の場合はカーソルを先頭に持ってくる
moveto 0, 0;
