// git show
if(filename==""){
    endmacro;
}

disablehistory 0x0041;

execmacro currentmacrodirectory + "\\sub_commit_hash_menu.mac";
$$commit_hash = getresultex(-1);
if($$commit_hash==""){
    endmacro;
}

// コミットハッシュの内容
$$git = "git.exe show ";
$$cmd = $$git + $$commit_hash + ":" + basename2;
runex $$cmd
    , 1         //sync   0:async, 1:sync
    , 0, ""     //stdin  0:none, 1:auto, 2:<file, 3:(reserved),
                //       4:current content, 5:selection
    , 4, ""     //stdout 0:none, 1:auto, 2:>file 3:>>file, 4:new window,
                //       5:insert, 6:replace, 7:>output pane, 8:>>output pane
    , 4, ""     //stderr 0:none, 1:auto or >>stdout, 2-8:same as stdout's param
    , 0, ""     //folder 0:none, 1:current, 2:specify 3:(reserved), 4:exe's
    , 2         //show   0:auto, 1:show, 2:hide, 3-13:ShellExecute()'s SW_*
    , 1         //draw   0:draw, 1:no draw when stdout redirected
    , 6         //encode 0:ansi, 2:utf-16, 6:utf-8
    , 0         //extended flags
;
if (result == 0) {
  message "gitのコマンド実行時にエラーが発生しました。\n" + $$cmd;
  endmacro;
}
//runex の引数が 4:new window の場合はカーソルを先頭に持ってくる
moveto 0, 0;
