// git show

##log_max_count = 60;
##max_width = 70;

disabledraw;
disablehistory 0x0041;

// メニュー用にログを取得する
$$git = "git.exe log -" + str(##log_max_count) + " --follow --no-merges --date=short --pretty=format:\"[%ad] %h %an : %s\" " ;
$$cmd = $$git + filename2;
$$dir = directory2 + "\\";
##current_handle = hidemaruhandle(0);

//new window
runex $$cmd
    , 1         //sync   0:async, 1:sync
    , 0, ""     //stdin  0:none, 1:auto, 2:<file, 3:(reserved),
                //       4:current content, 5:selection
    , 4, ""     //stdout 0:none, 1:auto, 2:>file 3:>>file, 4:new window,
                //       5:insert, 6:replace, 7:>output pane, 8:>>output pane
    , 4, ""     //stderr 0:none, 1:auto or >>stdout, 2-8:same as stdout's param
    , 2, $$dir     //folder 0:none, 1:current, 2:specify 3:(reserved), 4:exe's
    , 2         //show   0:auto, 1:show, 2:hide, 3-13:ShellExecute()'s SW_*
    , 1         //draw   0:draw, 1:no draw when stdout redirected
    , 6    //encode 0:ansi, 2:utf-16, 6:utf-8
    , 0         //extended flags
;
if(result==0){
    message "gitのコマンド実行時にエラーが発生しました。\n" + $$cmd;
    endmacro;
}
##tmp_handle = hidemaruhandle(0);
moveto 0,0;//ファイル先頭へ移動

$$comment = leftstr("■表示するコミットを選択してください■" + basename2,##max_width);
##start_row_index = 2;
##count = ##start_row_index;
$$menu[0] = $$comment;
$$menu[1] = "\x01";
while (##count <= ##log_max_count + ##start_row_index) {
  if (result == false){
    break;
  }
  beginclipboardread;
  beginlinesel 0;
  copy;
  $$menu[##count] = leftstr(getclipboard,##max_width);
  down;
  ##count = ##count + 1;
}
enabledraw;
setactivehidemaru ##current_handle;
closehidemaru ##tmp_handle;

// メニューを表示する
menuarray $$menu,##count;
##idx = result;

$$commit_hash = "";
if (##idx > ##start_row_index) {
  // 選択されたメニューからコミットハッシュを取り出す
  $$commit_hash = midstr($$menu[##idx - 1], 13, 7);
}
if (strlen($$commit_hash) != 7) {
  endmacro;
}

// コミットハッシュの内容
$$git = "git.exe show ";
$$cmd = $$git + $$commit_hash + ":" + basename2;
runex $$cmd
    , 1         //sync   0:async, 1:sync
    , 0, ""     //stdin  0:none, 1:auto, 2:<file, 3:(reserved),
                //       4:current content, 5:selection
    , 4, ""     //stdout 0:none, 1:auto, 2:>file 3:>>file, 4:new window,
                //       5:insert, 6:replace, 7:>output pane, 8:>>output pane
    , 4, ""     //stderr 0:none, 1:auto or >>stdout, 2-8:same as stdout's param
    , 0, ""     //folder 0:none, 1:current, 2:specify 3:(reserved), 4:exe's
    , 2         //show   0:auto, 1:show, 2:hide, 3-13:ShellExecute()'s SW_*
    , 1         //draw   0:draw, 1:no draw when stdout redirected
    , 6         //encode 0:ansi, 2:utf-16, 6:utf-8
    , 0         //extended flags
;
if (result == 0) {
  message "gitのコマンド実行時にエラーが発生しました。\n" + $$cmd;
  endmacro;
}
//runex の引数が 4:new window の場合はカーソルを先頭に持ってくる
moveto 0, 0;
